sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: UuRiRlHLoYOVYX2zz90E4ixX1LnKV8bbZJwjyRIyZHGHfM77O8w17pabCe1PCFszWwIkASgFNOK4Kgptje69v7xZvfeU6r39sfkQvR7Msy4NOlPk/lWr9r6NvUmhdP7VaQaglwGeZ9Nmm/g3t+XdXI1Lsy7+XUln0RXTTl13SdH5xQpOONNi4z1VisglmOHx5k99dXsSd9d/F5HdHJPSR7227pxAKXGpdtSARDbtHFKTYes2THMV6V/jZc6QE4aUfcnt9LNa3hmaotrwD+MEHNLKZh9rNyJmB9Q2LowiLa7q7dWJZ1CLd2u/WIk631/pGr1zT903azsC6OmCjkx4xl1DtFuZMDNsFLsjSpSiYN0d3jWtIf4442uY7xLcjv/N2/0QzxyK5+HH7DgYebtC1qB6GjPhyInHu0kKIJMAzwBmOZLCFd+z93QBgONxocvr1Yfp6mdv2gMETJpsPhMlPeHE7U47AiDetDwyN77LmNgES/oDhURM3kU5j/TUyyJV0ISpREpu/p5oLvlU7KE+vDseSCgWcN3CjWoeL55svfUB+fPqoioL4DcVL+UJ/MNEN6HfKUjZVyfgtAjCOzdoUfCXXC3etml0h0QgLllb7YzK4Tl1clWK2OmbqvSGiEiwyV2x10O5kBxDRODJaycALxou2+YhBvdfNvJKhn40C5A=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Woman-Hater_3669
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy